### PR TITLE
DropDowm Bug fixed

### LINKED ISSUE #243: Dropdown/TimeZone bug fixes
- Fix the PropTypes for the DropDown component to match what is being used inside the component
- Fix TimeZone to send `name` and not `value`
- Fix TimeZone story to use `value` and `setValue`

### PR DESCRIPTION
**Pull request by Yaser-Aldammad**
# Description
change PropTypes in DropDowm component

Fixes #243 

# How to test?
Storybook

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

File: src/client/components/TimeZone/TimeZone.component.js [hunk 1]
```diff
@@ -19,15 +19,15 @@ TimeZoneDropDown.propTypes = {
...
     shape({
       id: PropTypes.number,
-      value: PropTypes.string,
+      name: PropTypes.string,
     }),
   ),
-  timeZone: PropTypes.string,
-  setTimeZone: PropTypes.func,
+  name: PropTypes.string,
+  setName: PropTypes.func,
```
Comment (tpetrina) [inline src/client/components/TimeZone/TimeZone.component.js:26]: Actually, the old name was better. Since you are picking a time zone, it is more natural to have: `<TimeZone timeZone="UTC" />` than `<TimeZone name="UTC" />`. But it is not really important.

**Review by tpetrina — APPROVED** [review]
Nice fix!

**Review by Elia-Git — APPROVED** [review]
Good job!
